standard = [
  "clapper",
  "cliphist",
  "cmake",
  "delfin",
  "docker",
  "docker-buildx",
  "docker-compose",
  "duckdb",
  "duf",
  "ffmpegthumbnailer",
  "fwupd",
  "ghostty",
  "git",
  "git-delta",
  "glow",
  "helium-browser-bin",
  "lazygit",
  "localsend",
  "mediainfo",
  "neovim",
  "nvtop",
  "nwg-look",
  "opendesktop-fonts",
  "otf-geist-mono-nerd",
  "ouch",
  "qbittorrent",
  "qt5-graphicaleffects",
  "qt5ct",
  "qt6-5compat",
  "qt6ct",
  "resvg",
  "sox",
  "sqlc",
  "starship",
  "stow",
  "swappy",
  "texinfo",
  "tk",
  "tmux",
  "tree",
  "tree-sitter-cli",
  "unrar",
  "unzip",
  "uv",
  "vim",
  "yazi",
  "zen-browser-bin",
  "zig",
  "zoxide",
]

aur = [
  "1password",
  "1password-cli",
  "datagrip",
  "datagrip-jre",
  "discord_arch_electron",
  "f2-bin",
  "ivpn",
  "ivpn-ui",
  "nemo-preview",
  "nyaa-bin",
  "postman-bin",
  "sddm-silent-theme",
  "tagselecta-bin",
  "tsukimi-bin",
  "v4l2ucp-qt5",
  "zmk-studio-bin",
  "zoom",
]

flatpak = [
]

