monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-Kanto_Audio_ORA_by_Kanto_20240130-00" }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
        audio.position = ["FR", "FL"]
      }
    }
  }
]
