stow -t ~ hypr
stow -t ~ ghostty-linux
stow -t ~ btop
stow -t ~ bat
stow -t ~ nvim
stow -t ~ starship
stow -t ~ swappy
stow -t ~ swaylock
stow -t ~ rofi
stow -t ~ waybar
stow -t ~ wlogout
stow -t ~ tmux-linux
stow -t ~ zsh-linux
